[GB.NET.CURL] * BUG: Add missing error opcodes in old curl libraries.
CNet.c:136: error: ‘CURLE_FTP_PRET_FAILED’ undeclared here (not in a
function)
CNet.c:139: error: ‘CURLE_FTP_BAD_FILE_LIST’ undeclared here (not in a
function)
CNet.c:140: error: ‘CURLE_CHUNK_FAILED’ undeclared here (not in a
function)
make[4]: *** [CNet.lo] Errore 1



git-svn-id: svn://localhost/gambas/trunk@4089 867c0c6c-44f3-4631-809d-bfa615b0a4ec