[DB.FIREBIRD] * BUG: Fix building with gcc-4.6.0
make[4]: Entering directory `/build/src/gambas2-2.23.1/gb.db.firebird/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I.. -I./ibpp/core   -pipe -Wall -fno-exceptions 
-Wno-unused-value -Wcast-align -fsigned-char -fvisibility=hidden -g -Os -fno-omit-frame-pointer -fexceptions  -MT 
gb_db_firebird_la-main.lo -MD -MP -MF .deps/gb_db_firebird_la-main.Tpo -c -o gb_db_firebird_la-main.lo `test -f 'main.cpp' || 
echo './'`main.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I./ibpp/core -pipe -Wall -fno-exceptions -Wno-unused-value -Wcast-align 
-fsigned-char -fvisibility=hidden -g -Os -fno-omit-frame-pointer -fexceptions -MT gb_db_firebird_la-main.lo -MD -MP -MF 
.deps/gb_db_firebird_la-main.Tpo -c main.cpp  -fPIC -DPIC -o .libs/gb_db_firebird_la-main.o
main.cpp: In function 'int query_fill(DB_DATABASE*, DB_RESULT, int, GB_VARIANT_VALUE*, int)':
main.cpp:1219:44: error: taking address of temporary [-fpermissive]
main.cpp: In function 'int field_info(DB_DATABASE*, const char*, const char*, DB_FIELD*)':
main.cpp:1903:48: error: taking address of temporary [-fpermissive]
main.cpp:1905:36: error: taking address of temporary [-fpermissive]
make[4]: *** [gb_db_firebird_la-main.lo] Error 1
make[4]: Leaving directory `/build/src/gambas2-2.23.1/gb.db.firebird/src'



git-svn-id: svn://localhost/gambas/branches/2.0@3865 867c0c6c-44f3-4631-809d-bfa615b0a4ec